---
  - name: Install packages
    apt:
      name:
      - nginx
      - unzip
      - php7.4-zip
      - php-imagick
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
      update_cache: yes

  - name: Wordpress nginx configuration
    template:
      src: example.com.conf.j2
      dest: /etc/nginx/sites-enabled/default

  - name: Download wordpress
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html/
      remote_src: yes 
 
  - name: File permissions
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'
  
  - name: Wordpress configuration file
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Edit php.ini add save_handler
    ansible.builtin.lineinfile:
      path: /etc/php/7.4/fpm/php.ini
      regexp: "session.save_handler = files" 
      line: "session.save_handler = memcached"
      state: present

  - name: Edit php.ini add remove save_path
    ansible.builtin.lineinfile:
      path: /etc/php/7.4/fpm/php.ini
      regexp: "session.save_path" 
      state: absent

  - name: Edit php.ini add remove save_path
    ansible.builtin.lineinfile:
      path: /etc/php/7.4/fpm/php.ini
      line: "session.save_path = {{memcached_endpoint}}"
      state: present
 
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

  - name: Restart php7.4-fpm
    service:
      name: php7.4-fpm
      state: restarted
